import { describe, it, expect } from 'vitest';
import { formatReportAsHTML, formatReportAsMarkdown, formatReportAsJSON } from './formatters.js';
import type { GenerationReport } from './types.js';

describe('Report Formatters', () => {
  const mockReport: GenerationReport = {
    version: '1.0',
    metadata: {
      reportId: 'test-report-id-123',
      generatedAt: '2025-01-15T10:30:00.000Z',
      generatorVersion: '0.1.0',
      hostname: 'test-host',
    },
    input: {
      schemaFile: 'test.vague',
      schemaHash: 'abc123def456',
    },
    attestation: {
      generatedAt: '2025-01-15T10:30:00.000Z',
      generator: 'vague v0.1.0',
      seed: 42,
      schemaHash: 'abc123def456',
      statement:
        'This data was synthetically generated by Vague. It does not contain real personal information.',
    },
    summary: {
      totalRecords: 100,
      totalCollections: 2,
      seed: 42,
      constraintsSatisfied: 98,
      constraintsTotal: 100,
      constraintSatisfactionRate: 98,
      warningsCount: 2,
    },
    collections: [
      {
        name: 'invoices',
        schemaName: 'Invoice',
        recordCount: 50,
        fields: [
          {
            name: 'id',
            type: 'number',
            count: 50,
            nullCount: 0,
            nullPercentage: 0,
            uniqueCount: 50,
            cardinality: 100,
            numeric: {
              min: 1,
              max: 50,
              mean: 25.5,
              median: 25.5,
              stdDev: 14.5,
            },
          },
          {
            name: 'status',
            type: 'string',
            count: 50,
            nullCount: 0,
            nullPercentage: 0,
            uniqueCount: 3,
            cardinality: 6,
            distribution: [
              { value: 'paid', count: 25, percentage: 50 },
              { value: 'draft', count: 15, percentage: 30 },
              { value: 'sent', count: 10, percentage: 20 },
            ],
          },
        ],
        constraints: {
          total: 2,
          satisfied: 2,
          details: [],
        },
      },
    ],
    warnings: [
      {
        type: 'ConstraintRetryLimit',
        message: 'Test warning',
      },
    ],
    performance: {
      totalDurationMs: 150,
      recordsPerSecond: 667,
      constraintSolvingMs: 50,
      constraintSolvingPercentage: 33.3,
    },
    comparisons: [
      {
        field: 'invoices.status',
        divergence: 0.15,
        significant: false,
        baseline: {
          distribution: [
            { value: 'paid', percentage: 45 },
            { value: 'draft', percentage: 35 },
            { value: 'sent', percentage: 20 },
          ],
        },
        current: {
          distribution: [
            { value: 'paid', percentage: 50 },
            { value: 'draft', percentage: 30 },
            { value: 'sent', percentage: 20 },
          ],
        },
      },
    ],
  };

  describe('formatReportAsHTML', () => {
    it('generates valid HTML document', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('<!DOCTYPE html>');
      expect(html).toContain('<html lang="en">');
      expect(html).toContain('</html>');
    });

    it('includes report title', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('Vague Generation Report');
    });

    it('includes attestation statement', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('Synthetic Data Attestation');
      expect(html).toContain('synthetically generated');
    });

    it('includes summary statistics', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('100'); // Total records
      expect(html).toContain('98.0%'); // Constraint satisfaction rate
      expect(html).toContain('42'); // Seed
    });

    it('includes collection details', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('invoices');
      expect(html).toContain('Invoice');
      expect(html).toContain('50 records');
    });

    it('includes field statistics', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('id');
      expect(html).toContain('status');
      expect(html).toContain('number');
      expect(html).toContain('string');
    });

    it('includes warnings when present', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('Warnings');
      expect(html).toContain('ConstraintRetryLimit');
    });

    it('includes distribution changes when comparisons provided', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('Distribution Changes from Baseline');
      expect(html).toContain('invoices.status');
    });

    it('includes metadata section', () => {
      const html = formatReportAsHTML(mockReport);

      expect(html).toContain('Report Metadata');
      expect(html).toContain('abc123def456'); // Schema hash
      expect(html).toContain('test.vague');
    });
  });

  describe('formatReportAsMarkdown', () => {
    it('generates valid markdown with headers', () => {
      const md = formatReportAsMarkdown(mockReport);

      expect(md).toContain('# Vague Generation Report');
      expect(md).toContain('## Summary');
      expect(md).toContain('## Collections');
    });

    it('includes attestation as blockquote', () => {
      const md = formatReportAsMarkdown(mockReport);

      expect(md).toContain('## Synthetic Data Attestation');
      expect(md).toContain('> ');
    });

    it('includes summary table', () => {
      const md = formatReportAsMarkdown(mockReport);

      expect(md).toContain('| Metric | Value |');
      expect(md).toContain('| Total Records | 100 |');
      expect(md).toContain('| Seed | 42 |');
    });

    it('includes collection tables', () => {
      const md = formatReportAsMarkdown(mockReport);

      expect(md).toContain('### invoices (Invoice)');
      expect(md).toContain('| Field | Type | Null % | Unique | Cardinality |');
    });

    it('includes warnings as list', () => {
      const md = formatReportAsMarkdown(mockReport);

      expect(md).toContain('## Warnings');
      expect(md).toContain('- **ConstraintRetryLimit**');
    });

    it('includes comparison table when comparisons provided', () => {
      const md = formatReportAsMarkdown(mockReport);

      expect(md).toContain('## Distribution Changes from Baseline');
      expect(md).toContain('`invoices.status`');
    });

    it('includes metadata as list', () => {
      const md = formatReportAsMarkdown(mockReport);

      expect(md).toContain('## Report Metadata');
      expect(md).toContain('- **Generator:**');
      expect(md).toContain('- **Schema Hash:**');
    });
  });

  describe('formatReportAsJSON', () => {
    it('returns valid JSON', () => {
      const json = formatReportAsJSON(mockReport);

      const parsed = JSON.parse(json);
      expect(parsed).toBeDefined();
    });

    it('is pretty-printed', () => {
      const json = formatReportAsJSON(mockReport);

      expect(json).toContain('\n');
      expect(json).toContain('  '); // Indentation
    });

    it('preserves all report data', () => {
      const json = formatReportAsJSON(mockReport);
      const parsed = JSON.parse(json);

      expect(parsed.version).toBe('1.0');
      expect(parsed.metadata.reportId).toBe('test-report-id-123');
      expect(parsed.summary.totalRecords).toBe(100);
      expect(parsed.collections).toHaveLength(1);
    });
  });

  describe('edge cases', () => {
    it('handles report with no warnings', () => {
      const reportNoWarnings = { ...mockReport, warnings: [] };
      const html = formatReportAsHTML(reportNoWarnings);
      const md = formatReportAsMarkdown(reportNoWarnings);

      // Should not include warnings section when empty
      expect(html).not.toContain('class="warning-item"');
      expect(md.split('## Warnings').length).toBe(1); // No warnings section
    });

    it('handles report with no comparisons', () => {
      const reportNoComparisons = { ...mockReport, comparisons: undefined };
      const html = formatReportAsHTML(reportNoComparisons);
      const md = formatReportAsMarkdown(reportNoComparisons);

      expect(html).not.toContain('Distribution Changes from Baseline');
      expect(md).not.toContain('Distribution Changes from Baseline');
    });

    it('handles report with null seed', () => {
      const reportRandomSeed = { ...mockReport, summary: { ...mockReport.summary, seed: null } };
      const html = formatReportAsHTML(reportRandomSeed);
      const md = formatReportAsMarkdown(reportRandomSeed);

      expect(html).toContain('Random');
      expect(md).toContain('Random');
    });
  });
});
